/**
 * Initial board content — the real SafeWayHome work, across the four teams.
 * Stable ids so concurrent first-run seeding by two peers converges (no duplicates).
 * Statuses/estimates reflect roughly where the project stands so the board is meaningful day one.
 *   status: 'todo' | 'doing' | 'done'  ·  estimateH / spentH in hours
 */
export const SEED = [
  // ───────────────────────────── Backend ─────────────────────────────
  { id: 'seed_db', category: 'backend', sub: 'Databas', status: 'done', estimateH: 16, spentH: 16,
    title: 'PostgreSQL-databaslager',
    description: 'Fullt datalager (10 tabeller) så data bara kan läggas in senare.',
    approach: 'SQLAlchemy 2.0 + PostGIS + pgvector, Alembic-migreringar, Docker. Byggt och adversariellt granskat.' },
  { id: 'seed_api', category: 'backend', sub: 'API-server', status: 'done', estimateH: 12, spentH: 14,
    title: 'FastAPI-bryggan',
    description: 'REST-API mellan React-frontend och Python-kärnan.',
    approach: 'FastAPI + uvicorn på 8011; /route /context /safe-havens /geocode /walk-route /fsm.' },
  { id: 'seed_dsro', category: 'backend', sub: 'DSRO-routing', status: 'doing', estimateH: 24, spentH: 14,
    title: 'DSRO säkerhetsrouting',
    description: 'Dynamisk säker ruttoptimering över gångnätet.',
    approach: 'networkx + H3, per-kant safety_score; väg samman incidenter, infrastruktur och belysning.',
    deps: ['seed_db', 'seed_osm'] },
  { id: 'seed_fsm', category: 'backend', sub: 'On-device FSM', status: 'doing', estimateH: 18, spentH: 9,
    title: 'On-device krisläges-FSM',
    description: 'Duress/Acoustic/Kinetic-tillståndsmaskin på enheten.',
    approach: 'numpy + onnxruntime; PIN/nödkod, ljud- och rörelsetrösklar.', deps: ['seed_api'] },
  { id: 'seed_integr', category: 'backend', sub: 'Integrationer', status: 'doing', estimateH: 10, spentH: 5,
    title: 'Officiella datakällor',
    description: 'SMHI väder, Trafiklab kollektivtrafik, NVDB väg.',
    approach: 'official_data.py; cacha + normalisera till DSRO-vikter.' },
  { id: 'seed_drive', category: 'backend', sub: 'Infra & Drive', status: 'done', estimateH: 6, spentH: 7,
    title: 'Drive-artefaktlagring',
    description: 'Stora artefakter utanför git → Google Drive, hämtas automatiskt.',
    approach: 'Lazy OAuth, upload/download_tree, scripts/drive_sync.py.' },
  { id: 'seed_setup', category: 'backend', sub: 'Infra & Drive', status: 'done', estimateH: 8, spentH: 10,
    title: 'Dev-miljö & setup',
    description: 'En-kommandos uppsättning av allt (LLMs, deps, venv).',
    approach: 'setup_dev_env.sh; python@3.11, validate_system grön.' },

  // ──────────────────────────── Datainsamling ────────────────────────
  { id: 'seed_police', category: 'data', sub: 'Polisens API', status: 'done', estimateH: 8, spentH: 8,
    title: 'Polisens händelse-API',
    description: 'Lagliga brottshändelser per ort.',
    approach: 'fetch_police_events.py; direkt mot officiella API:t, ingen Nominatim.' },
  { id: 'seed_tdm', category: 'data', sub: 'TDM-medieinsamling', status: 'done', estimateH: 12, spentH: 13,
    title: 'TDM-medieinsamling',
    description: 'Nyhetsinsamling under EU:s TDM-undantag.',
    approach: 'scrape_news_tdm.py; fail-closed PII-scrubb, GDPR-skydd. (Olaglig scraping borttagen.)',
    deps: ['seed_police'] },
  { id: 'seed_havens', category: 'data', sub: 'Safe havens', status: 'doing', estimateH: 8, spentH: 4,
    title: 'Safe havens-insamling',
    description: 'Öppna trygga punkter dygnet runt (mackar, sjukhus, polis).',
    approach: 'Hämta + geokoda; lägg i safe_havens-tabellen.', deps: ['seed_db'] },
  { id: 'seed_osm', category: 'data', sub: 'OSM-vägnät', status: 'doing', estimateH: 14, spentH: 7,
    title: 'OSM gång-vägnät',
    description: 'Bygg routbart gångnät för en stad (Umeå).',
    approach: 'osmnx → route_nodes / route_segments (oriktade kanter).', deps: ['seed_db'] },
  { id: 'seed_embed', category: 'data', sub: 'Embeddings / loop', status: 'todo', estimateH: 16, spentH: 0,
    title: 'Self-rewarding loop + embeddings',
    description: 'Inkrementell förbättring via incident-matchning.',
    approach: 'ChromaDB + all-MiniLM-L6-v2 + Ollama; pgvector HNSW i prod.', deps: ['seed_tdm', 'seed_db'] },

  // ───────────────────────────── Utveckling ──────────────────────────
  { id: 'seed_onb', category: 'dev', sub: 'Onboarding & konto', status: 'doing', estimateH: 10, spentH: 5,
    title: 'Onboarding & BankID-behörighet',
    description: 'Inloggning + behörighetskoll (lagrar aldrig personnummer).',
    approach: 'Eligibility-boolean; mockad BankID i prototypen.' },
  { id: 'seed_map', category: 'dev', sub: 'Karta & navigation', status: 'done', estimateH: 10, spentH: 11,
    title: 'OSM-karta i appen',
    description: 'Riktig OpenStreetMap med trygga rutter.',
    approach: 'Leaflet + CARTO voyager light; z-index isolerad så kartan inte täcker UI.' },
  { id: 'seed_nav', category: 'dev', sub: 'Karta & navigation', status: 'done', estimateH: 12, spentH: 13,
    title: 'Adress-till-adress gångnavigering',
    description: 'Skriv vart du ska → snabbaste gångvägen, antal min/km.',
    approach: 'Nominatim geocode + OSRM foot + GPS-origin.', deps: ['seed_map'] },
  { id: 'seed_crisis', category: 'dev', sub: 'Krisläge / FSM-UI', status: 'doing', estimateH: 14, spentH: 6,
    title: 'Krislägesgränssnitt',
    description: 'Tyst nödläge, nedräkning, guardian-larm.',
    approach: 'SecurityContext speglar FSM-enums; överlägg + haptik.', deps: ['seed_fsm'] },
  { id: 'seed_guard', category: 'dev', sub: 'Guardian-vy', status: 'doing', estimateH: 10, spentH: 4,
    title: 'Guardian-vy (vakta min promenad)',
    description: 'Väktare ser live-position och incheckningar.',
    approach: 'walk_sessions; live GPS-ström; tysta larm.', deps: ['seed_nav'] },
  { id: 'seed_theme', category: 'dev', sub: 'Design & tema', status: 'done', estimateH: 8, spentH: 9,
    title: 'Design & tema (gräddvit + rosa)',
    description: 'Varmt, ljust, mindre formellt nattläge.',
    approach: 'Claude Design-handoff; rose #fb7185, Nunito.' },
  { id: 'seed_board', category: 'dev', sub: 'Team-board', status: 'doing', estimateH: 10, spentH: 6,
    title: 'Team-board (denna sida)',
    description: 'Whiteboard + timeline + progress, i realtid för teamet.',
    approach: 'Yjs + Trystero (Nostr) P2P, React Flow-spindelnät; deployas på GitHub Pages.', deps: ['seed_theme'] },

  // ──────────────────────────── Marknadsföring ───────────────────────
  { id: 'seed_report', category: 'mkt', sub: 'Exjobb & rapport', status: 'doing', estimateH: 40, spentH: 12,
    title: 'Exjobbsrapport',
    description: 'Skriv och strukturera examensarbetet.',
    approach: 'Bakgrund, metod (DSRO/FSM), etik/GDPR, resultat.' },
  { id: 'seed_ethics', category: 'mkt', sub: 'Exjobb & rapport', status: 'done', estimateH: 6, spentH: 6,
    title: 'Etik & datalaglighet',
    description: 'Säkerställ lagliga datakällor + GDPR.',
    approach: 'Endast Polis-API + TDM; olaglig scraping borttagen och dokumenterad.', deps: ['seed_tdm'] },
  { id: 'seed_pitch', category: 'mkt', sub: 'Pitch & demo', status: 'todo', estimateH: 8, spentH: 0,
    title: 'Pitch & demo-flöde',
    description: 'Demoberättelse: från hot → trygg väg hem.',
    approach: 'Manus + seedad Umeå-data; skärmdumpar/inspelning.', deps: ['seed_crisis', 'seed_nav'] },
  { id: 'seed_landing', category: 'mkt', sub: 'Webb & landing', status: 'todo', estimateH: 10, spentH: 0,
    title: 'Landningssida',
    description: 'Publik sida som förklarar appen och teamet.',
    approach: 'Statisk sida; kan ligga på GitHub Pages bredvid denna board.' },
  { id: 'seed_usertest', category: 'mkt', sub: 'Användartester', status: 'todo', estimateH: 12, spentH: 0,
    title: 'Användartester (upplevd trygghet)',
    description: 'Testa upplevd trygghet nattetid med riktiga användare.',
    approach: 'Litet n; enkät + observation; iterera designen.', deps: ['seed_crisis'] },
]
